/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.VendedorController;
import javax.swing.JOptionPane;
import modelo.Validador;
import modelo.Vendedor;

/**
 *
 * @author Administrador
 */
public class AgregarVendedor extends javax.swing.JFrame {

    /**
     * Creates new form AgregarVendedor
     */
    public AgregarVendedor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAddVendedorMenu = new javax.swing.JButton();
        lblCreador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRutVendedor = new javax.swing.JLabel();
        lblDvVendedor = new javax.swing.JLabel();
        lblNombreVendedor = new javax.swing.JLabel();
        lblDireccionVendedor = new javax.swing.JLabel();
        lblMailVendedor = new javax.swing.JLabel();
        lblFonoVendedor = new javax.swing.JLabel();
        btnAddGuardar = new javax.swing.JButton();
        btnCleanAddVendedor = new javax.swing.JButton();
        txtAddRut = new javax.swing.JTextField();
        txtAddDvVendedor = new javax.swing.JTextField();
        txtAddNombreVendedor = new javax.swing.JTextField();
        txtAddDireccionVendedor = new javax.swing.JTextField();
        txtAddMailVendedor = new javax.swing.JTextField();
        txtAddFonoVendedor = new javax.swing.JTextField();
        btnAddVendedorVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CARmona Autos - Rent a car");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 236, 154));

        btnAddVendedorMenu.setBackground(new java.awt.Color(255, 236, 154));
        btnAddVendedorMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddVendedorMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnAddVendedorMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3643769-building-home-house-main-menu-start_113416.png"))); // NOI18N
        btnAddVendedorMenu.setText("Menu");
        btnAddVendedorMenu.setBorder(null);
        btnAddVendedorMenu.setContentAreaFilled(false);
        btnAddVendedorMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddVendedorMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddVendedorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVendedorMenuActionPerformed(evt);
            }
        });

        lblCreador.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblCreador.setForeground(new java.awt.Color(102, 102, 102));
        lblCreador.setText("Ivan Andres Duarte Herrera ®");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddVendedorMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblCreador)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddVendedorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblCreador))
        );

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("      CARmona Autos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Agregar Vendedor");

        lblRutVendedor.setForeground(new java.awt.Color(0, 0, 0));
        lblRutVendedor.setText("Rut:");

        lblDvVendedor.setForeground(new java.awt.Color(0, 0, 0));
        lblDvVendedor.setText("Digito verificador:");

        lblNombreVendedor.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreVendedor.setText("Nombre:");

        lblDireccionVendedor.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccionVendedor.setText("Direccion: ");

        lblMailVendedor.setForeground(new java.awt.Color(0, 0, 0));
        lblMailVendedor.setText("Correo electronico: ");

        lblFonoVendedor.setForeground(new java.awt.Color(0, 0, 0));
        lblFonoVendedor.setText("Telefono:");

        btnAddGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnAddGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnAddGuardar.setText("Guardar");
        btnAddGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGuardarActionPerformed(evt);
            }
        });

        btnCleanAddVendedor.setBackground(new java.awt.Color(255, 255, 255));
        btnCleanAddVendedor.setForeground(new java.awt.Color(0, 0, 0));
        btnCleanAddVendedor.setText("Limpiar");
        btnCleanAddVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanAddVendedorActionPerformed(evt);
            }
        });

        txtAddRut.setBackground(new java.awt.Color(255, 255, 255));
        txtAddRut.setForeground(new java.awt.Color(0, 0, 0));
        txtAddRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddRutKeyTyped(evt);
            }
        });

        txtAddDvVendedor.setBackground(new java.awt.Color(255, 255, 255));
        txtAddDvVendedor.setForeground(new java.awt.Color(0, 0, 0));

        txtAddNombreVendedor.setBackground(new java.awt.Color(255, 255, 255));
        txtAddNombreVendedor.setForeground(new java.awt.Color(0, 0, 0));

        txtAddDireccionVendedor.setBackground(new java.awt.Color(255, 255, 255));
        txtAddDireccionVendedor.setForeground(new java.awt.Color(0, 0, 0));

        txtAddMailVendedor.setBackground(new java.awt.Color(255, 255, 255));
        txtAddMailVendedor.setForeground(new java.awt.Color(0, 0, 0));

        txtAddFonoVendedor.setBackground(new java.awt.Color(255, 255, 255));
        txtAddFonoVendedor.setForeground(new java.awt.Color(0, 0, 0));
        txtAddFonoVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddFonoVendedorKeyTyped(evt);
            }
        });

        btnAddVendedorVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnAddVendedorVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnAddVendedorVolver.setText("Volver");
        btnAddVendedorVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVendedorVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblRutVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAddRut))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDvVendedor)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtAddDvVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblNombreVendedor)
                                                .addGap(26, 26, 26)
                                                .addComponent(txtAddNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(btnAddVendedorVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDireccionVendedor)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtAddDireccionVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblMailVendedor)
                                                    .addComponent(lblFonoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtAddMailVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                                    .addComponent(txtAddFonoVendedor)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(btnCleanAddVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutVendedor)
                    .addComponent(lblDireccionVendedor)
                    .addComponent(txtAddRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddDireccionVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDvVendedor)
                    .addComponent(lblMailVendedor)
                    .addComponent(txtAddDvVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddMailVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreVendedor)
                    .addComponent(lblFonoVendedor)
                    .addComponent(txtAddNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddFonoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnCleanAddVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddVendedorVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVendedorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVendedorMenuActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddVendedorMenuActionPerformed

    private void btnAddVendedorVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVendedorVolverActionPerformed
        ListarVendedor v = new ListarVendedor();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddVendedorVolverActionPerformed

    private void btnAddGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGuardarActionPerformed
        //obtener datos de los txt
        String rutVendedor, digVerVen, nombreVendedor,fonoVendedor, mailVendedor, direccionVendedor; 
        
        rutVendedor = this.txtAddRut.getText();
        digVerVen = this.txtAddDvVendedor.getText();
        nombreVendedor = this.txtAddNombreVendedor.getText();
        fonoVendedor = this.txtAddFonoVendedor.getText();
        mailVendedor = this.txtAddMailVendedor.getText();
        direccionVendedor = this.txtAddDireccionVendedor.getText();
        
        Validador v = new Validador();
        if (!v.validaVacio(rutVendedor)|| !v.validaVacio(digVerVen)|| !v.validaVacio(fonoVendedor)
            || !v.validaVacio(mailVendedor)|| !v.validaVacio(direccionVendedor)) { 
            JOptionPane.showMessageDialog(this, "Debe rellenar los campos vacios", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        Vendedor vendedor = new Vendedor(rutVendedor,digVerVen,nombreVendedor,direccionVendedor,mailVendedor,fonoVendedor);
        
        VendedorController rg = new VendedorController();
        
        //validador de rut de vendedor y dv, para no ingresar duplicado
        if (rg.buscarVendedor(rutVendedor).getRutVendedor()==null || rg.buscarDvVendedor(digVerVen).getDigVer()==null) {
            if(rg.agregarVendedor(vendedor)){
                JOptionPane.showMessageDialog(this,"Vendedor agregado","Infomacion", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this,"Error","Infomacion", JOptionPane.ERROR_MESSAGE);
            }        
        }else{
            JOptionPane.showMessageDialog(this, "N de rut de vendedor ya registrado: " + rutVendedor+"-"+digVerVen+ " Ya existe en la base de datos!", "Validación",JOptionPane.WARNING_MESSAGE ); 
        }
        
    }//GEN-LAST:event_btnAddGuardarActionPerformed

    private void btnCleanAddVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanAddVendedorActionPerformed
        this.txtAddRut.setText("");
        this.txtAddDvVendedor.setText("");
        this.txtAddNombreVendedor.setText("");
        this.txtAddFonoVendedor.setText("");
        this.txtAddMailVendedor.setText("");
        this.txtAddDireccionVendedor.setText("");
    }//GEN-LAST:event_btnCleanAddVendedorActionPerformed

    private void txtAddRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddRutKeyTyped
        //metodo para solo ingresar numeros
        int key = evt.getKeyChar();
        
        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAddRutKeyTyped

    private void txtAddFonoVendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddFonoVendedorKeyTyped
        //metodo para ingresar numeros
        int key = evt.getKeyChar();
        
        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAddFonoVendedorKeyTyped



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGuardar;
    private javax.swing.JButton btnAddVendedorMenu;
    private javax.swing.JButton btnAddVendedorVolver;
    private javax.swing.JButton btnCleanAddVendedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCreador;
    private javax.swing.JLabel lblDireccionVendedor;
    private javax.swing.JLabel lblDvVendedor;
    private javax.swing.JLabel lblFonoVendedor;
    private javax.swing.JLabel lblMailVendedor;
    private javax.swing.JLabel lblNombreVendedor;
    private javax.swing.JLabel lblRutVendedor;
    private javax.swing.JTextField txtAddDireccionVendedor;
    private javax.swing.JTextField txtAddDvVendedor;
    private javax.swing.JTextField txtAddFonoVendedor;
    private javax.swing.JTextField txtAddMailVendedor;
    private javax.swing.JTextField txtAddNombreVendedor;
    private javax.swing.JTextField txtAddRut;
    // End of variables declaration//GEN-END:variables
}
