
package vista;

import controlador.VendedorController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Validador;
import modelo.Vendedor;

/**
 *
 * @author Administrador
 */
public class ListarVendedor extends javax.swing.JFrame {

    VendedorController rgv = new VendedorController();
    

    public ListarVendedor() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //llenar jtable al inicio con la tabla vendedor
        String rutVendedor, digVerVen, nombreVendedor,fonoVendedor, mailVendedor, direccionVendedor; 
        DefaultTableModel modeloV = (DefaultTableModel) this.tblVendedor.getModel();
        
        modeloV.setRowCount(0);
        rutVendedor = this.txtRutVendedor.getText();
        if (rutVendedor.isEmpty()) {
            ArrayList<Vendedor> lista = rgv.llenarTableVendedores();
            for(Vendedor v: lista){
                rutVendedor = v.getRutVendedor();
                digVerVen = v.getDigVer();
                nombreVendedor = v.getNombreVendedor();
                fonoVendedor = v.getFonoVendedor();
                mailVendedor = v.getMailVendedor();
                direccionVendedor = v.getDireccionVendedor();
                
                modeloV.addRow(new Object[]{rutVendedor, digVerVen, nombreVendedor,fonoVendedor, mailVendedor, direccionVendedor});
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblCreador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVendedor = new javax.swing.JTable();
        btnDeleteVendedor = new javax.swing.JButton();
        btnEditVendedor = new javax.swing.JButton();
        btnAddVendedor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtRutVendedor = new javax.swing.JTextField();
        btnBuscarVendedor = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CARmona Autos - Rent a car");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 236, 154));

        jButton1.setBackground(new java.awt.Color(255, 236, 154));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3643769-building-home-house-main-menu-start_113416.png"))); // NOI18N
        jButton1.setText("Menu");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblCreador.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblCreador.setForeground(new java.awt.Color(102, 102, 102));
        lblCreador.setText("Ivan Andres Duarte Herrera ®");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblCreador)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblCreador))
        );

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("      CARmona Autos");

        tblVendedor.setBackground(new java.awt.Color(255, 255, 255));
        tblVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Dv", "Nombre", "Telefono", "Email", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVendedor);

        btnDeleteVendedor.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteVendedor.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteVendedor.setText("Eliminar vendedor");
        btnDeleteVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVendedorActionPerformed(evt);
            }
        });

        btnEditVendedor.setBackground(new java.awt.Color(255, 255, 255));
        btnEditVendedor.setForeground(new java.awt.Color(0, 0, 0));
        btnEditVendedor.setText("Editar vendedor");
        btnEditVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditVendedorActionPerformed(evt);
            }
        });

        btnAddVendedor.setBackground(new java.awt.Color(255, 255, 255));
        btnAddVendedor.setForeground(new java.awt.Color(0, 0, 0));
        btnAddVendedor.setText("Agregar vendedor");
        btnAddVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVendedorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Vendedor");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar rut sin puntos ni digito verificador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        txtRutVendedor.setBackground(new java.awt.Color(255, 255, 255));
        txtRutVendedor.setForeground(new java.awt.Color(0, 0, 0));
        txtRutVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutVendedorKeyTyped(evt);
            }
        });

        btnBuscarVendedor.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarVendedor.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarVendedor.setText("Buscar vendedor");
        btnBuscarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRutVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarVendedor)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVendedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnClean.setBackground(new java.awt.Color(255, 255, 255));
        btnClean.setForeground(new java.awt.Color(0, 0, 0));
        btnClean.setText("Recargar tabla");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDeleteVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(203, 203, 203)
                                .addComponent(btnEditVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(385, 385, 385)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(157, 157, 157)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVendedorActionPerformed
        DefaultTableModel modeloV = (DefaultTableModel) this.tblVendedor.getModel();
        modeloV.setRowCount(0); //limpiar tabla y mostrar solo 1 resultado
        
        String rutVendedor, digVerVen, nombreVendedor,fonoVendedor, mailVendedor, direccionVendedor; 

        rutVendedor = this.txtRutVendedor.getText();
        
        Validador v = new Validador();
        if (!v.validaVacio(rutVendedor)) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un rut", "Validación", JOptionPane.WARNING_MESSAGE);
            return;            
        }

        
        Vendedor vendedor = rgv.buscarVendedor(rutVendedor);
        digVerVen = vendedor.getDigVer();
        nombreVendedor = vendedor.getNombreVendedor();
        fonoVendedor = vendedor.getFonoVendedor();
        mailVendedor = vendedor.getMailVendedor();
        direccionVendedor = vendedor.getDireccionVendedor();
        
        //rellenar fila de la jtable
        modeloV.addRow(new Object[]{rutVendedor, digVerVen, nombreVendedor,fonoVendedor, mailVendedor, direccionVendedor});

        
    }//GEN-LAST:event_btnBuscarVendedorActionPerformed

    private void btnEditVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditVendedorActionPerformed
        int fila = this.tblVendedor.getSelectedRow(); //validar fila seleccionada para editar
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila", "Validación", JOptionPane.WARNING_MESSAGE);
            this.tblVendedor.requestFocus();
            return;
        } else{
            
            Vendedor vendedor = new Vendedor();
            
            vendedor.setRutVendedor((String) this.tblVendedor.getValueAt(fila, 0));
            vendedor.setDigVer((String) this.tblVendedor.getValueAt(fila, 1));
            vendedor.setNombreVendedor((String) this.tblVendedor.getValueAt(fila, 2));
            vendedor.setFonoVendedor((String) this.tblVendedor.getValueAt(fila, 3));
            vendedor.setMailVendedor((String) this.tblVendedor.getValueAt(fila, 4));
            vendedor.setDireccionVendedor((String) this.tblVendedor.getValueAt(fila, 5));
            
            
            ModificarVendedor mv = new ModificarVendedor(vendedor);
            mv.setVisible(true);
            this.setVisible(false);            
        }        
        
        
        

    }//GEN-LAST:event_btnEditVendedorActionPerformed

    private void btnAddVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVendedorActionPerformed
        AgregarVendedor av = new AgregarVendedor();
        av.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddVendedorActionPerformed

    private void btnDeleteVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVendedorActionPerformed
        int fila = this.tblVendedor.getSelectedRow();
        //comprobar que se selecciono una fila 
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila", "Validación", JOptionPane.WARNING_MESSAGE);
            this.tblVendedor.requestFocus();
            return;
        } else { //de haberse seleccionado se comprobará rut
            String rutVendedor = (String) this.tblVendedor.getValueAt(fila, 0);
            if (rgv.eliminarVendedor(rutVendedor)) {
                JOptionPane.showMessageDialog(this, "Se eliminó correctamente el vendedor con rut: " + rutVendedor, "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se eliminó el vendedor con rut: " + rutVendedor, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteVendedorActionPerformed

    private void txtRutVendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutVendedorKeyTyped
        
        //metodo para solo ingresar numeros
        int key = evt.getKeyChar();
        
        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRutVendedorKeyTyped

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        ListarVendedor lv = new ListarVendedor();
        lv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCleanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVendedor;
    private javax.swing.JButton btnBuscarVendedor;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDeleteVendedor;
    private javax.swing.JButton btnEditVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreador;
    private javax.swing.JTable tblVendedor;
    private javax.swing.JTextField txtRutVendedor;
    // End of variables declaration//GEN-END:variables
}
